version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: music_postgres
    restart: always
    environment:
      POSTGRES_USER: ricardo
      POSTGRES_PASSWORD: 1234  # Change this to your actual password
      POSTGRES_DB: sql_study
    ports:
      - "5433:5432"
    volumes:
      # This maps your local scripts to the container's init folder
      - ./scripts/db-init:/docker-entrypoint-initdb.d
      # This persists your data even if the container is deleted
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: